// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADhLaMRAocyTbpPCibOnwFeZSn-LkvVjU',
    appId: '1:416094018507:web:c3a3e2c9ab4c1299a5f44e',
    messagingSenderId: '416094018507',
    projectId: 'riderpay-e22aa',
    authDomain: 'riderpay-e22aa.firebaseapp.com',
    storageBucket: 'riderpay-e22aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsGVmFQFeHVGdrIdFjnk-kFdCY8oOFQIs',
    appId: '1:416094018507:android:2bea14f8d66b8956a5f44e',
    messagingSenderId: '416094018507',
    projectId: 'riderpay-e22aa',
    storageBucket: 'riderpay-e22aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuk_uKU-2kTogVHI8Pv9hK5xQRdzljDdA',
    appId: '1:416094018507:ios:c203e507c8de0092a5f44e',
    messagingSenderId: '416094018507',
    projectId: 'riderpay-e22aa',
    storageBucket: 'riderpay-e22aa.firebasestorage.app',
    iosBundleId: 'com.example.shubhDriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuk_uKU-2kTogVHI8Pv9hK5xQRdzljDdA',
    appId: '1:416094018507:ios:c203e507c8de0092a5f44e',
    messagingSenderId: '416094018507',
    projectId: 'riderpay-e22aa',
    storageBucket: 'riderpay-e22aa.firebasestorage.app',
    iosBundleId: 'com.example.shubhDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADhLaMRAocyTbpPCibOnwFeZSn-LkvVjU',
    appId: '1:416094018507:web:61828c6813f5bad5a5f44e',
    messagingSenderId: '416094018507',
    projectId: 'riderpay-e22aa',
    authDomain: 'riderpay-e22aa.firebaseapp.com',
    storageBucket: 'riderpay-e22aa.firebasestorage.app',
  );

}